### ISSUE TITLE
2FA does not check if it is the same email in the authentication application

### ISSUE THREAD

**Issue by fernandogiroto** [kind-work/two-fa#41]
I installed 2fa in the project following all the steps. I scan the QR Code and put the numbers created in the authentication app and it works. The problem is that I log in from an account that does not belong to me and is not configured in the authentication app and it works normally. In other words, I don't need to be using the same email that I logged into statamic in the authentication app.

**Comment by jcohlmeyer** [comment]
1. It is unsafe to share this QR code/key as it would allow anyone to generate the 2FA code required to log into your account. **If this key is currently in use, make sure you replace it ASAP by disabling 2FA and then re-enabling it.**
2. Did you, by chance, click on the `Remember me` check box when you filled in your 2FA code? If you did, this means that you will not be asked for the account's 2FA code again in this browser until the cookie expires (or is cleared).

Otherwise, I can not reproduce the behaviour you are experiencing.
